name: Nightly CSV to Excel Sync

on:
  schedule:
    - cron: '0 7 * * *'  # midnight Pacific
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas openpyxl

      - name: Append CSV to Excel
        id: append
        run: python scripts/append_to_excel.py

      - name: Create timestamped backup
        if: steps.append.outcome == 'success' && steps.append.conclusion == 'success'
        run: |
          mkdir -p streamlit/data/backups
          timestamp=$(date +'%Y-%m-%d_%H-%M-%S')
          cp "data/September Averages.xlsx" "streamlit/data/backups/September_Averages_${timestamp}.xlsx"

      - name: Commit and push changes
        if: steps.append.conclusion == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout main || git checkout -b main
          
          git add "data/September Averages.xlsx" "streamlit/data/backups/September_Averages_"*.xlsx || true
          if ! git diff --cached --quiet; then
            git commit -m "Nightly sync + backup: append or update Excel"
            git push origin main
          else
            echo "No changes to commit."
          fi

      - name: Publish summary to workflow run
        if: always()
        run: |
          echo "### 🧾 Nightly Sync Summary" >> $GITHUB_STEP_SUMMARY
          if [ -f sync_summary.md ]; then
            cat sync_summary.md >> $GITHUB_STEP_SUMMARY
          else
            echo "_No summary file found._" >> $GITHUB_STEP_SUMMARY
          fi
